D_kart/urls.py
from django.conf.urls.static import static
from django.urls import path,include
from django.conf import settings
from django.contrib import admin



urlpatterns = [

    
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('category/',include('category.urls')),
    path('store/',include('store.urls')),
    path('admin_panel/',include('admin_panel.urls')),
    path('cart/',include('carts.urls')),
    path('orders/',include('orders.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from unicodedata import name
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart, name = 'cart'),
    path('add_cart/<int:product_id>/',views.add_cart, name= 'add_cart'),
    path('remove_cart',views.remove_cart, name= 'remove_cart'),    
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item, name= 'remove_cart_item'),  
    path('checkout/',views.checkout, name='checkout'), 
    path('add_btn_cart/',views.add_btn_cart, name='add_btn_cart'), 


]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('',views.home, name = 'home')
]

store/urls.py
from unicodedata import name
from django.urls import path
from . import views
urlpatterns = [
    path('',views.store, name = 'store'),
    
    path('<slug:category_slug>/',views.store,name = 'products_by_category'),
    path('brand/<slug:brand_slug>/',views.brand_store, name ='products_by_brand'),
    path('<slug:category_slug>/<slug:product_slug>/',views.product_detail,name ='product_detail'),
    path('price_filter',views.price_filter,name='price_filter')
    
]

store/models.py
from ast import Sub
from random import choice, choices
from tokenize import blank_re
from unicodedata import category
from wsgiref.simple_server import demo_app
from django.forms import CharField
from django.urls import reverse
from django.db import models
from accounts.models import Account
# Create your models here.
from category.models import Category, SubCategory
from django.db.models import CharField, Model
from django_mysql.models import ListCharField
from django.core.validators import MinValueValidator,MaxValueValidator

class Product(models.Model):
    brand = models.ForeignKey(SubCategory, on_delete=models.CASCADE,null=True)
    product_name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    offer_price = models.IntegerField(default=0)
    offer = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(90)])
    images = models.ImageField(upload_to='images/products', blank=True)
    images_two = models.ImageField(upload_to='images/products', blank=True)
    images_three = models.ImageField(upload_to='images/products', blank=True)
    stock = models.PositiveIntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)
    # size  = ListCharField(base_field=CharField(max_length=10),size = 4,max_length =(4 * 11),null = True)
    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category = 'color', is_active = True)
    
    def sizes(self):
        return super(VariationManager,self).filter(variation_category = 'size', is_active = True)
    
variation_category_choice = (
    ('color', 'color'), 
    ('size', 'size'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices = variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()
    
    class Meta:
        verbose_name        = 'Variation'
        verbose_name_plural = 'Variation'

        verbose_name_plural = 'Variations'
    def __str__(self):
        return self.variation_value

class Banner(models.Model):
    banner_title = models.CharField(max_length=50,blank=True)
    banner_img1 = models.ImageField(upload_to='images/banner',blank = True)
    banner_img2 = models.ImageField(upload_to='images/banner',blank = True)


    def __str__(self):
        return self.banner_title
class Wishlist(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)

carts/views.py
import re
from statistics import quantiles
from django.shortcuts import get_object_or_404, redirect, render
from django.core.exceptions import ObjectDoesNotExist
from carts.models import Cart, CartItem
from django.http import HttpResponse, JsonResponse
from orders.models import AddressTable
from store.models import Product, Variation
from doctest import Example
from urllib import request
from django import http
from math import prod
from django.db.models import Q

##views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id) #get the product

    # If the user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        if int(request.POST['buy_now_btn'])==0:


            is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
            print(product_variation)
            if is_cart_item_exists:
                cart_item = CartItem.objects.filter(product=product, user=current_user)
                ex_var_list = []
                id = []
                for item in cart_item:
                    existing_variation = item.variations.all()[::-1]
                    ex_var_list.append(list(existing_variation))
                    id.append(item.id)
                print(ex_var_list)
                if product_variation in ex_var_list:
                    # increase the cart item quantity
                    index = ex_var_list.index(product_variation)
                    item_id = id[index]
                    item = CartItem.objects.get(product=product, id=item_id)
                    item.quantity += 1
                    item.save()

                else:
                    item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                    if len(product_variation) > 0:
                        item.variations.clear()
                        item.variations.add(*product_variation)
                    item.save()
            else:
                cart_item = CartItem.objects.create(
                    product = product,
                    quantity = 1,
                    user = current_user,
                )
                if len(product_variation) > 0:
                    cart_item.variations.clear()
                    cart_item.variations.add(*product_variation)
                cart_item.save()
            return redirect('cart')
        else:
            a=''
            for i in product_variation:
                a+=str(i.id)+'-'
            request.session['buy_now']=a
            print(request.session['buy_now'])
            print('=============================================hhhhhhhhhhhhhhhhhhh')
            return redirect('checkout')
    # If the user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass


        try:
            cart = Cart.objects.get(cart_id=_cart_id(request)) # get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()
        print(product_variation)
        is_cart_item_exists = CartItem.objects.filter(Q(product=product) & Q(cart=cart)).exists()
        if is_cart_item_exists:
            print('ffd-------------------------------------------------------------')
            cart_item = CartItem.objects.filter(Q(product=product) & Q(cart=cart))
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()[::-1]
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            print(ex_var_list)
            if product_variation in ex_var_list :
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product = product,id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product =product, quantity = 1,cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save() 
            


        
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
            return redirect('cart')
        
    


def add_btn_cart(request):
    mid=int(request.GET['mid'])
    total = float(request.GET['total'])
    cartitem = CartItem.objects.get(id=mid) #get the product
    if cartitem.product.stock > cartitem.quantity:
        cartitem.quantity += 1
        cartitem.save()
        sub_total = cartitem.sub_total()
        grand_total = total + cartitem.product.offer_price
        context ={
            'qty':cartitem.quantity,
            'sub':sub_total,
            'gt':grand_total,
            'f':0
        }
        return JsonResponse(context)
    else:
        return JsonResponse({'f':1})
        


def remove_cart(request):
    id=int(request.GET['mid'])
    total = float(request.GET['total'])
    cart_item = CartItem.objects.get(id = id)
    cart_item.quantity -= 1
    cart_item.save()
    sub_total = cart_item.sub_total()
    grand_total = total - cart_item.product.offer_price
    cart_item.save()
    context ={
            'qty':cart_item.quantity,
            'sub':sub_total,
            'gt':grand_total,
        }
    return JsonResponse(context)

def remove_cart_item(request,product_id,cart_item_id):
    product = get_object_or_404(Product, id = product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product= product, user = request.user,id = cart_item_id)
    else:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        product = get_object_or_404(Product, id = product_id)
        cart_item = CartItem.objects.get(product = product, cart = cart ,id = cart_item_id)
    cart_item.delete()
    return redirect('cart')


def cart(request,total =0,quantity = 0,cart_items =None):
    if request.session.has_key('buy_now'):
        del request.session['buy_now']
    grand_total = 0
    try:
        if request.user.is_authenticated:
    
            cart_items = CartItem.objects.filter(user = request.user,is_active =True)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_items = CartItem.objects.filter(cart = cart,is_active =True)
        for cart_item in cart_items:
            total += (cart_item.product.offer_price * cart_item.quantity)
            quantity += cart_item.quantity
        
    except ObjectDoesNotExist:
        pass
    grand_total = total
    context = {
        'total': total,
        'quantity' : quantity,
        'cart_items': cart_items,
        'grand_total':grand_total,
    }
    return render(request,'store/cart.html' ,context)



def checkout(request,total =0,quantity = 0,cart_items =None):
    if request.user.is_authenticated:
        if request.session.has_key('email'):
            
            add_table =  AddressTable.objects.filter(user = request.user)
            if request.session.has_key('buy_now'):
                variation = request.session['buy_now']
                var_id=variation.split('-')
                print(var_id)
                varient=Variation.objects.get(id=int(var_id[0]))
                pro=Product.objects.get(id=varient.product.id)
                total=pro.offer_price
                grand_total=pro.offer_price
                quantity=1
                cart_items=None
            else:
                    cart_items = CartItem.objects.filter(user = request.user,is_active =True)
                    for cart_item in cart_items:
                        total += (cart_item.product.offer_price * cart_item.quantity)
                        quantity += cart_item.quantity
                    grand_total = total 
                    pro=None
                    
            context = {
            'total': total,
            'quantity' : quantity,
            'cart_items': cart_items,
            'grand_total':grand_total,
            'add_table':add_table,
            'pro':pro

        }     
            return render(request,'store/checkout.html',context)
                
    return redirect('login')

store/views.py
from ast import Sub
from traceback import print_tb
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from store.models import Product
from category.models import Category, SubCategory
from carts.models import Cart, CartItem
from carts.views import _cart_id
# Create your views here.

def store(request,category_slug = None):
    
    categories = None
    products = None
    if category_slug != None:
        categories= get_object_or_404(Category, slug = category_slug)
        # print(categories.id)
        products = Product.objects.filter(category= categories,is_available = True)
        # print(products)
        cat_offer = categories.category_offer
        for i in products:
            product_offer = i.offer
            if (cat_offer >= product_offer):
                print(cat_offer)
                i.offer_price =round((i.price *(1-(cat_offer/100))),2)
            else:
                i.offer_price  = round((i.price*(1-(product_offer/100))),2)
            i.save()
        product_count = products.count()


    else:
        products = Product.objects.all().filter(is_available = True)
        product_count = products.count()
    context = {
        'products':products,
        'product_count':product_count,
    }
    return render(request,'store/store.html',context)

def brand_store(request,brand_slug=None):
    brands = None
    products = None
    print('this is brand slug going to print')
    if brand_slug != None:
        print('this is brand slug going to print')
        print(brand_slug)
        # categories= get_object_or_404(Category, slug = category_slug)
        brands = get_object_or_404(SubCategory,slug = brand_slug)
        products = Product.objects.filter(brand = brands,is_available = True)
        print(products)
        print('--------products by brand')
        product_count = products.count()
    else:
        print('else condition going to print')
        products = Product.objects.all().filter(is_available = True)
        product_count = products.count()

    context = {
        'products':products,
        'product_count':product_count,
    }
    return render(request,'store/store.html',context)

def product_detail(request,category_slug=None,product_slug=None):
    try:
        print('single product')
        categories= get_object_or_404(Category, slug = category_slug)
        single_product = Product.objects.get(slug= product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id = _cart_id(request),product = single_product).exists()
       
        cat_offer = categories.category_offer
        print(single_product)
    except Exception as e:
        raise e
    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'cat_offer':cat_offer,
    }
    return render(request,'store/product_detail.html',context)

def price_filter(request):
    min = request.GET['min'] 
    max = request.GET['max'] 
   
    price_filter = Product.objects.filter(offer_price__gte=min, offer_price__lte = max)
   
    # print(price_filter)
    context = {
        'products':price_filter,
    }
    
    return render(request,'store/store.html',context)

templates/store/a.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Font Awesome -->

</head>

<body>




    <!-- MDB -->

</body>

</html>

templates/store/product_detail.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}


<section class="section-content bg-white padding-y">
    <div class="container">

        <!-- ============================ ITEM DETAIL ======================== -->
        <div class="row">
            <aside class="col-md-6">
                <div class="card">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div> <a href="#"><img src="{{ single_product.images.url }}"
                                        data-zoom-image={{single_product.images.url}} id="zoom" class="ProductImg"></a>
                            </div>
                        </div> <!-- slider-product.// -->
                        <div class="thumbs-wrap">
                            <a href="" class="item-thumb"> <img src="{{ single_product.images.url }}"
                                    class="small-img"></a>
                            <a href="" class="item-thumb"> <img src="{{ single_product.images_two.url }}"
                                    class="small-img"></a>
                            <a href="" class="item-thumb"> <img src="{{ single_product.images_three.url }}"
                                    class="small-img"></a>
                        </div> <!-- slider-nav.// -->
                    </article> <!-- gallery-wrap .end// -->
                </div> <!-- card.// -->
            </aside>
            <main class="col-md-6 border-left card">
                <form action="{% url 'add_cart' single_product.id %}" method="POST" id="add_to_cart">
                    {% csrf_token %}
                    <article class="content-body">

                        <h3>{{ single_product.brand}}</h3>

                        <h2 class="title">{{ single_product.product_name }}</h2>
                        {% if single_product.category.category_offer > 0 or single_product.offer > 0 %}
                        <div class="mb-3">
                          
                            <var class="price h4">${{ single_product.offer_price }}</var>
                            <del>${{single_product.price}}</del>
                            {% if single_product.category.category_offer >= single_product.offer %}
                            <span style="color: rgb(34, 235, 44);">({{ single_product.category.category_offer}}% off)</span>
                            {% else %}
                            <span style="color: rgb(34, 235, 44);">({{ single_product.offer}}% off)</span>

                            {% endif %}


                        </div>
                        {% else %}
                        <div class="price-wrap mt-2">
                            <var class="price h4">${{ single_product.price }}</var>

                        </div>
                       
                        {% endif %}
                        <p>{{ single_product.description }}</p>


                        <hr>
                        {% if single_product.stock <= 0 %}
                       

                       
                        
                        <h2 class="text-danger" style="font-weight: 600;"> Out of Stock </h2>
                        {% else %}
                        <hr>
                        <div class="row">

                            <div class="item-option-select">
                                <h6>Select Size</h6>
                                <select name="size" class="form-control" id="size">
                                    <option disabled selected>select</option>
                                    {% for i in single_product.variation_set.sizes %}
                                    <option value="{{ i.variation_value }}">{{ i.variation_value }}</option>
                                    {% endfor %}
                                </select>

                                <p id="color-err" style="color: red;"></p>
                            </div>
                            <div class="item-option-select">
                                <h6>Choose Color</h6>
                                <select name="color" class="form-control" id="color" required>
                                    <option disabled selected>select</option>
                                    {% for i in single_product.variation_set.colors %}
                                    <option value="{{ i.variation_value }}">{{ i.variation_value }}</option>
                                    {% endfor %}
                                </select>
                                <p id="size-err" style="color: red;"></p>
                            </div>

                        </div>

                        <input type="hidden" name="buy_now_btn" value="" id="buy_now_btn">
                        <button type="button" class="btn  btn-primary" id="add_cart_btn"> <span class="text">Add to cart</span> <i
                                class="fas fa-shopping-cart"></i> </button>
                        <button type="button" class="btn btn-warning" id="buy_now">Buy Now</button>
                        <!-- <button type="submit" class="btn  btn-primary"> <span class="text">Buy Now</span> <i class="fas fa-shopping-cart"></i> </button> -->

                        <!-- <a href="{% url 'add_cart' single_product.id %}" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i> </a> -->
                        {% endif %}
                    </article>
                </form>
                <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->

        <!-- ================ ITEM DETAIL END .// ================= -->


    </div> <!-- container .//  -->
</section>
<!-- Elevate Zoom JS -->
<script src="{% static 'custom/user_product/js/jquery.elevateZoom-3.0.8.min.js' %}"></script>
<script>
    $("#zoom").elevateZoom({
        zoomType: 'inner',
        cursor: 'crosshair'
    });


    jQuery("#elevate-zoom").elevateZoom({
        gallery: 'more-vies',
        lensSize: 200,
        cursor: 'pointer',
        galleryActiveClass: 'active',
        imageCrossfade: true,
        scrollZoom: true,
        responsive: true
    });
</script>
<script>
    var ProductImg = document.getElementById("zoom");
    var SmallImg = document.getElementsByClassName("small-img");
    SmallImg[0].onclick = function () {
        ProductImg.src = SmallImg[0].src;

    }
    SmallImg[1].onclick = function () {
        ProductImg.src = SmallImg[1].src;
    }
    SmallImg[2].onclick = function () {
        ProductImg.src = SmallImg[2].src;
    }
</script>
<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'></script>
<script src='https://sachinchoolur.github.io/lightslider/dist/js/lightslider.js'></script>

<script>

    document.getElementById('add_cart_btn').addEventListener("click", function(){


        var color = document.getElementById("color").value;
        var size  = document.getElementById("size").value;
        document.getElementById('buy_now_btn').value = '0'
        



        if(size == 'select'){
            document.getElementById("color-err").innerHTML='select size';
        } else if(color == 'select'){
            document.getElementById("color-err").innerHTML='';
            document.getElementById("size-err").innerHTML='select color';
        }else{
            document.getElementById("add_to_cart").submit()
        }

    })
    document.getElementById('buy_now').addEventListener("click", function(){

        document.getElementById('buy_now_btn').value = '1'
        console.log(document.getElementById('buy_now_btn').value)

        var color = document.getElementById("color").value;
        var size  = document.getElementById("size").value;



        if(size == 'select'){
            document.getElementById("color-err").innerHTML='select size';
        } else if(color == 'select'){
            document.getElementById("color-err").innerHTML='';
            document.getElementById("size-err").innerHTML='select color';
        }else{
            document.getElementById("add_to_cart").submit()
        }

    })
    
</script>
{% endblock content %}